version: 2
jobs:
  build: 
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout  
      - restore_cache:
          keys:
            - rubyvis-{{ checksum "Gemfile.lock" }}
            - rubyvis-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubyvis-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name:  Run rspec
          command: bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb")
      - store_test_results:
          path: test_results
